# SPDX-License-Identifier: MIT
---
- name: Remove snapshots from previous runs
  ansible.builtin.script: "{{ __snapshot_cmd }}"
  args:
    executable: "{{ __snapshot_python }}"
  register: snapshot_cmd
