---
- name: Snapshot All VGs
  ansible.builtin.script: "{{ __cmd }}"
  args:
    executable: "{{ __snapshot_python }}"
  register: snapshot_cmd
  vars:
    __cmd: "{{ 'snapshot.py snapshot ' ~
      ('-a ' if snapshot_lvm_all_vgs == true else '') ~
      '-r ' ~ (snapshot_lvm_percent_space_required | quote) ~ ' ' ~
      '-p ' ~ (snapshot_lvm_prefix | quote) ~ ' ' ~
      '-vg ' ~ (snapshot_lvm_vg | quote) ~ ' ' ~
      '-lv ' ~ (snapshot_lvm_lv | quote) ~ ' ' ~
      '-s ' ~ (snapshot_lvm_suffix | quote) }}"
  failed_when: snapshot_cmd.rc != 0
