---
- name: Verify snapshot clean is completed
  ansible.builtin.script: >-
    snapshot.py clean -a -v -p {{ snapshot_lvm_prefix | quote }}
    -s {{ snapshot_lvm_suffix | quote }}
  register: snapshot_cmd
  args:
    executable: "{{ ansible_python.executable }}"
  failed_when:
    snapshot_cmd.rc != 0
